/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package umkm;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class Pemesanan extends javax.swing.JFrame {

    /**
     * Creates new form Pemesanan
     */
    
    
    Statement stm;
    String idlevel;
    int hargatotal,checkout;
    public Pemesanan(String level) throws SQLException{
        initComponents();
         koneksi con = new koneksi();
        stm = (Statement) con.getConnection().createStatement();
        this.idlevel = level;
        if(idlevel.equals("2")){
            
            jMenu1.setVisible(false);
        }
        
        
        
        this.select();
    }
    
    public void select() throws SQLException{
        String query = "select * from "+cbtersedia.getSelectedItem()+" WHERE status_"+cbtersedia.getSelectedItem()+" = 'tersedia'";
        ResultSet rs = stm.executeQuery(query);
        while(rs.next()){
            this.insertTable(rs.getString(1),rs.getString(2),rs.getString(3),rs.getString(4),rs.getString(5));
        }
    }
        
    public void insertTable(String id, String nama,String size, String harga, String status){
        DefaultTableModel model = (DefaultTableModel) tbtersedia.getModel();
        model.addRow(new Object[] {id,nama,size,harga,status});
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        cbtersedia = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbtersedia = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        tfkodekerajinan = new javax.swing.JTextField();
        tfkodepakaian = new javax.swing.JTextField();
        tfnama = new javax.swing.JTextField();
        tfharga = new javax.swing.JTextField();
        tfjumlah = new javax.swing.JTextField();
        tfketerangan = new javax.swing.JTextField();
        tfstatus = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbpesanan = new javax.swing.JTable();
        btntambah = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        tfpesanan = new javax.swing.JTextField();
        tfmeja = new javax.swing.JTextField();
        cbketerangan = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        tfkodekuliner = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        tfkodesnack = new javax.swing.JTextField();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenuItem7 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));

        jButton2.setBackground(new java.awt.Color(255, 0, 0));
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("X");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton2)
                .addGap(84, 84, 84))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(0, 204, 204));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Tersedia :");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(544, 25, -1, -1));

        cbtersedia.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cbtersedia.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "pakaian", "kerajinan", "kuliner", "snack", " " }));
        cbtersedia.setToolTipText("");
        cbtersedia.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cbtersediaMouseClicked(evt);
            }
        });
        cbtersedia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbtersediaActionPerformed(evt);
            }
        });
        jPanel2.add(cbtersedia, new org.netbeans.lib.awtextra.AbsoluteConstraints(657, 25, -1, 29));

        tbtersedia.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "id", "Nama", "Size", "Harga", "Status"
            }
        ));
        tbtersedia.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbtersediaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbtersedia);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(544, 70, 439, 221));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Pemesanan :");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(32, 25, -1, -1));
        jPanel2.add(tfkodekerajinan, new org.netbeans.lib.awtextra.AbsoluteConstraints(371, 70, 86, -1));

        tfkodepakaian.setToolTipText("");
        tfkodepakaian.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfkodepakaianActionPerformed(evt);
            }
        });
        jPanel2.add(tfkodepakaian, new org.netbeans.lib.awtextra.AbsoluteConstraints(147, 70, 85, -1));
        jPanel2.add(tfnama, new org.netbeans.lib.awtextra.AbsoluteConstraints(87, 158, 276, -1));
        jPanel2.add(tfharga, new org.netbeans.lib.awtextra.AbsoluteConstraints(87, 200, 276, -1));

        tfjumlah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfjumlahActionPerformed(evt);
            }
        });
        jPanel2.add(tfjumlah, new org.netbeans.lib.awtextra.AbsoluteConstraints(87, 244, 276, -1));
        jPanel2.add(tfketerangan, new org.netbeans.lib.awtextra.AbsoluteConstraints(87, 286, 276, -1));

        tfstatus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfstatusActionPerformed(evt);
            }
        });
        jPanel2.add(tfstatus, new org.netbeans.lib.awtextra.AbsoluteConstraints(87, 333, 276, -1));

        tbpesanan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Kode Order", "Kode Pakaian", "Kode Kerajinan", "Kode Kuliner", "Kode Snack", "Keterangan", "Status", "Jumlah", "Total"
            }
        ));
        jScrollPane2.setViewportView(tbpesanan);

        jPanel2.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(32, 466, 907, 168));

        btntambah.setText("Tambah");
        btntambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btntambahActionPerformed(evt);
            }
        });
        jPanel2.add(btntambah, new org.netbeans.lib.awtextra.AbsoluteConstraints(186, 421, -1, -1));

        jLabel3.setText("Kode Pakaian");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(32, 73, 84, -1));

        jLabel4.setText("Nama");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(32, 161, -1, -1));

        jLabel5.setText("Harga");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(32, 203, -1, -1));

        jLabel6.setText("Jumlah");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(32, 244, -1, -1));

        jLabel7.setText("Size");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(32, 289, -1, -1));

        jLabel8.setText("Status");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(32, 333, -1, -1));

        jLabel9.setText("Kode Kerajinan");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 73, -1, -1));
        jPanel2.add(tfpesanan, new org.netbeans.lib.awtextra.AbsoluteConstraints(142, 377, 85, -1));
        jPanel2.add(tfmeja, new org.netbeans.lib.awtextra.AbsoluteConstraints(328, 377, 129, -1));

        cbketerangan.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Ditunggu", "Ditinggal" }));
        cbketerangan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbketeranganActionPerformed(evt);
            }
        });
        jPanel2.add(cbketerangan, new org.netbeans.lib.awtextra.AbsoluteConstraints(583, 661, -1, -1));

        jButton1.setText("Check Out");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(728, 660, -1, -1));

        jLabel10.setText("Kode Order");
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(43, 380, -1, -1));

        jLabel11.setText("No Antrian");
        jPanel2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(236, 380, -1, -1));

        jLabel12.setText("Keterangan");
        jPanel2.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(489, 664, -1, -1));

        jLabel13.setText("Kode Kuliner");
        jPanel2.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(32, 108, -1, -1));
        jPanel2.add(tfkodekuliner, new org.netbeans.lib.awtextra.AbsoluteConstraints(147, 105, 84, -1));

        jLabel14.setText("Kode Snack");
        jPanel2.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(249, 108, -1, -1));
        jPanel2.add(tfkodesnack, new org.netbeans.lib.awtextra.AbsoluteConstraints(371, 105, 86, -1));

        jMenu1.setText("Master");

        jMenuItem1.setText("Snack");
        jMenuItem1.setToolTipText("");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuItem2.setText("Kuliner");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuItem6.setText("Pakaian");
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem6ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem6);

        jMenuItem7.setText("Kerajinan");
        jMenuItem7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem7ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem7);

        jMenuItem3.setText("User");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem3);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Transaksi");

        jMenuItem4.setText("Pemesanan");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem4);

        jMenuItem5.setText("Pembayaran");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem5);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(60, Short.MAX_VALUE))
        );

        setSize(new java.awt.Dimension(981, 850));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void cbtersediaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cbtersediaMouseClicked
        // TODO add your handling code here:
        DefaultTableModel tableModel = new DefaultTableModel();
        tableModel.addColumn("id");
        tableModel.addColumn("nama");
        tableModel.addColumn("size");
        tableModel.addColumn("harga");
        tableModel.addColumn("status");
        String kode = (String) cbtersedia.getSelectedItem();
        String query = "select * from "+cbtersedia.getSelectedItem()+" WHERE status_"+cbtersedia.getSelectedItem()+" = 'tersedia'";
        
        try {
            stm.executeQuery(query);
            ResultSet rs = stm.executeQuery(query);
            while (rs.next()) {
                tableModel.addRow(new Object[]{rs.getString(1), rs.getString(2), rs.getString(3), rs.getString(4), rs.getString(5)});
            }
            tbtersedia.setModel(tableModel);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error : "+e.getMessage());
        }
        
        
    }//GEN-LAST:event_cbtersediaMouseClicked

    private void cbtersediaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbtersediaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbtersediaActionPerformed

    private void tbtersediaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbtersediaMouseClicked
        // TODO add your handling code here:
        int row = tbtersedia.rowAtPoint(evt.getPoint());
        String id = tbtersedia.getValueAt(row, 0).toString();
        String nama = tbtersedia.getValueAt(row, 1).toString();
        String harga = tbtersedia.getValueAt(row, 3).toString();
        String status = tbtersedia.getValueAt(row, 4).toString();
        String size = tbtersedia.getValueAt(row, 2).toString();
        if(cbtersedia.getSelectedItem() == "pakaian"){
            tfkodepakaian.setText(id);
            tfkodekerajinan.setText("");
            tfkodekuliner.setText("");
            tfkodesnack.setText("");
        }if(cbtersedia.getSelectedItem() == "kerajinan"){
            tfkodekerajinan.setText(id);
            tfkodepakaian.setText("");
            tfkodekuliner.setText("");
            tfkodesnack.setText("");
        }if(cbtersedia.getSelectedItem() == "kuliner"){
            tfkodekuliner.setText(id);
            tfkodepakaian.setText("");
            tfkodekerajinan.setText("");
            tfkodesnack.setText("");
        }if(cbtersedia.getSelectedItem() == "snack"){
            tfkodesnack.setText(id);
            tfkodepakaian.setText("");
            tfkodekerajinan.setText("");
            tfkodekuliner.setText("");
        }
        tfnama.setText(nama);
        tfharga.setText(harga);
        tfstatus.setText(status);
        tfketerangan.setText(size);
    }//GEN-LAST:event_tbtersediaMouseClicked

    private void tfjumlahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfjumlahActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfjumlahActionPerformed

    private void tfkodepakaianActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfkodepakaianActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfkodepakaianActionPerformed

    private void tfstatusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfstatusActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfstatusActionPerformed

    private void btntambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btntambahActionPerformed
        // TODO add your handling code here:
        try{
            hargatotal = Integer.parseInt(tfharga.getText()) * Integer.parseInt(tfjumlah.getText());
            checkout += hargatotal;
            String query ="INSERT INTO detail_order VALUES('', '"
            +tfpesanan.getText() +"', '"
            +tfkodepakaian.getText() +"', '"
            +tfkodekerajinan.getText() +"', '"
            +tfkodekuliner.getText() +"', '"
            +tfkodesnack.getText() +"', '"
            +tfketerangan.getText()+"', '"
            +tfstatus.getText()+"', '"
            +tfjumlah.getText()+"');";

            stm.executeUpdate(query);

//            JOptionPane.showMessageDialog(null, "Berhasil ditambahkan!");

            //JOptionPane.showMessageDialog(null, "Berhasil ditambahkan!");

            this.insertTable(tfpesanan.getText(),tfkodepakaian.getText(),tfkodekerajinan.getText(),tfkodekuliner.getText(),tfkodesnack.getText(),tfketerangan.getText(), tfstatus.getText(), tfjumlah.getText());
            this.clear();
            selectTersedia();
        }

        catch (Exception e){
            JOptionPane.showMessageDialog(null,"On Save : " +e.getMessage());
        }
    }//GEN-LAST:event_btntambahActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
        
        
        try{
            String query1 ="INSERT INTO orderan VALUES('"
            +tfpesanan.getText() +"', '"+tfmeja.getText() +"',now(),'null','"+cbketerangan.getSelectedItem()+"','aktif');";
            
            String query3 ="INSERT INTO transaksi VALUES('"+tfpesanan.getText().toString()+"','"+idlevel+"', '"+tfpesanan.getText().toString()+"',now(),"+checkout+");";
            
            
            
            String query2 ="UPDATE detail_order set id_detail_order='"
            +tfpesanan.getText()+"',id_order='"
            +tfpesanan.getText()+"' WHERE id_order = '';";

            stm.executeUpdate(query1);
            stm.executeUpdate(query2);
            stm.executeUpdate(query3);

            JOptionPane.showMessageDialog(null, "Berhasil Check Out!");

            this.insertTable(tfpesanan.getText(),tfkodepakaian.getText(),tfkodekerajinan.getText(),tfkodekuliner.getText(),tfkodesnack.getText(),tfketerangan.getText(), tfstatus.getText(), tfjumlah.getText());
            this.clear();
            this.resetTable();
            selectTersedia();
        }

        catch (Exception e){
            JOptionPane.showMessageDialog(null, "On save : " +e.getMessage());
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        try {
            // TODO add your handling code here:
            new Snack(idlevel).show();
            this.setVisible(false);
        } catch (SQLException ex) {
            Logger.getLogger(menu.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        // TODO add your handling code here:
          try {
            // TODO add your handling code here:
            new user(idlevel).show();
            this.setVisible(false);
        } catch (SQLException ex) {
            Logger.getLogger(minuman.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        // TODO add your handling code here:
        try {
            // TODO add your handling code here:
            new Pemesanan(idlevel).show();
            this.setVisible(false);
        } catch (SQLException ex) {
            Logger.getLogger(menu.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        // TODO add your handling code here:
        try {
            // TODO add your handling code here:
            new transaksi(idlevel).show();
            this.setVisible(false);
        } catch (SQLException ex) {
            Logger.getLogger(menu.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        try {
            // TODO add your handling code here:
            new Kuliner(idlevel).show();
            this.setVisible(false);
        } catch (SQLException ex) {
            Logger.getLogger(Pemesanan.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        System.exit(0);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed
        try {
            // TODO add your handling code here:
            new Pakaian(idlevel).show();
            this.setVisible(false);
        } catch (SQLException ex) {
            Logger.getLogger(menu.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jMenuItem6ActionPerformed

    private void jMenuItem7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem7ActionPerformed
        try {
            // TODO add your handling code here:
            new Kerajinan(idlevel).show();
            this.setVisible(false);
        } catch (SQLException ex) {
            Logger.getLogger(menu.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jMenuItem7ActionPerformed

    private void cbketeranganActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbketeranganActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbketeranganActionPerformed

private void insertTable(String id_detail_order, String kode_pakaian, String kode_kerajinan, String kode_kuliner, String kode_snack, String keterangan,  String status, String jumlah) {
        //To change body of generated methods, choose Tools | Templates.
        DefaultTableModel model = (DefaultTableModel) tbpesanan.getModel();
        
        model.addRow(new Object[]{id_detail_order,kode_pakaian, kode_kerajinan,kode_kuliner, kode_snack, keterangan, status, jumlah,hargatotal});
    }


 
private void clear() {
        //To change body of generated methods, choose Tools | Templates.
//        tfpesanan.setText("");
        tfkodepakaian.setText("");
        tfkodekerajinan.setText("");
        tfkodekuliner.setText("");
        tfkodesnack.setText("");
        tfnama.setText("");
        tfnama.setText("");
        tfketerangan.setText("");
        tfstatus.setText("");
        tfjumlah.setText("");
        
    }

private void resetTable(){
    DefaultTableModel model = (DefaultTableModel) tbpesanan.getModel();
    model.setRowCount(0);
}

private void selectTersedia() {
         //To change body of generated methods, choose Tools | Templates.
         DefaultTableModel tableModel = new DefaultTableModel();
        tableModel.addColumn("id");
        tableModel.addColumn("nama");
        tableModel.addColumn("size");
        tableModel.addColumn("harga");
        tableModel.addColumn("status");
        String kode = (String) cbtersedia.getSelectedItem();
        String query = "SELECT * FROM "+cbtersedia.getSelectedItem()+" WHERE status_"+cbtersedia.getSelectedItem()+" = 'tersedia'";

        try {
            stm.executeQuery(query);
            ResultSet rs = stm.executeQuery(query);
            while (rs.next()){
                tableModel.addRow(new Object[]{rs.getString(1), rs.getString(2), rs.getString(3), rs.getString(4), rs.getString(5)});
            }
            tbtersedia.setModel(tableModel);
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, "Error : "+ex.getMessage());
        }
         
    }
    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btntambah;
    private javax.swing.JComboBox<String> cbketerangan;
    private javax.swing.JComboBox<String> cbtersedia;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tbpesanan;
    private javax.swing.JTable tbtersedia;
    private javax.swing.JTextField tfharga;
    private javax.swing.JTextField tfjumlah;
    private javax.swing.JTextField tfketerangan;
    private javax.swing.JTextField tfkodekerajinan;
    private javax.swing.JTextField tfkodekuliner;
    private javax.swing.JTextField tfkodepakaian;
    private javax.swing.JTextField tfkodesnack;
    private javax.swing.JTextField tfmeja;
    private javax.swing.JTextField tfnama;
    private javax.swing.JTextField tfpesanan;
    private javax.swing.JTextField tfstatus;
    // End of variables declaration//GEN-END:variables
}
